"""add username and password to users

Revision ID: 769d9b38ea93
Revises: 001
Create Date: 2026-01-12 05:03:23.046767+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769d9b38ea93'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversations_updated_at', table_name='conversations')
    op.drop_index('idx_conversations_user_id', table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_index('idx_messages_conversation_id', table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True, comment='密码哈希'))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index('idx_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index('idx_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_index('idx_conversations_updated_at', 'conversations', ['updated_at'], unique=False)
    # ### end Alembic commands ###
