/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    CitySelector: typeof import('./components/common/CitySelector.vue')['default']
    ConversationList: typeof import('./components/layout/ConversationList.vue')['default']
    DataCard: typeof import('./components/market/DataCard.vue')['default']
    DistrictTable: typeof import('./components/market/DistrictTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FavoritePanel: typeof import('./components/favorite/FavoritePanel.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoanForm: typeof import('./components/calculator/LoanForm.vue')['default']
    PolicyCard: typeof import('./components/common/PolicyCard.vue')['default']
    PriceChart: typeof import('./components/market/PriceChart.vue')['default']
    ResultCard: typeof import('./components/calculator/ResultCard.vue')['default']
    RoleMessage: typeof import('./components/chat/RoleMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaxForm: typeof import('./components/calculator/TaxForm.vue')['default']
    ThinkingProcess: typeof import('./components/chat/ThinkingProcess.vue')['default']
    ToolPanel: typeof import('./components/layout/ToolPanel.vue')['default']
    TotalCostForm: typeof import('./components/calculator/TotalCostForm.vue')['default']
  }
}
